package Entities;

public enum Speciality {
    THERAPIST,
    SURGEON,
    NEUROLOGIST,
    OPHTHALMOLOGIST,
    TRAUMATOLOGY,
    OBSTETRICIAN_GYNAECOLOGIST,
    UROLOGIST,
    ONCOLOGIST,
    ENDOCRINOLOGIST,
    DENTIST
}
